INFO  2022-08-03 15:58:51,472 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-03 17:25:21,355 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
ERROR  2022-08-03 17:25:39,070 Internal Server Error: /doLogin/
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "shikshalaya_computer_app_customuser" does not exist
LINE 1: ...alaya_computer_app_customuser"."profile_pic" FROM "shikshala...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\views.py", line 23, in doLogin
    user = EmailBackEnd.authenticate(request,username = request.POST.get('email'),password = request.POST.get('password'))
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\EmailBackEnd.py", line 9, in authenticate
    user = UserModel.objects.get(email=username)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 492, in get
    num = len(clone)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 302, in __len__
    self._fetch_all()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "shikshalaya_computer_app_customuser" does not exist
LINE 1: ...alaya_computer_app_customuser"."profile_pic" FROM "shikshala...
                                                             ^

WARNING  2022-08-03 17:25:39,352 Not Found: /favicon.ico
ERROR  2022-08-03 17:32:08,327 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 448, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

INFO  2022-08-03 17:35:04,608 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 17:41:56,480 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 17:42:17,677 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 17:42:29,667 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 17:42:34,372 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 17:42:57,988 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 461, in VIEW_COMPUTER_STUDENT
    conn = psycopg2.connect(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

INFO  2022-08-03 17:45:27,605 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 17:45:34,141 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 468, in VIEW_COMPUTER_STUDENT
    mf = cursor.execute("select Student_id, sum(month_fees) as sum_month_fees from shikshalaya_computer_app_computer_student_monthly_fees group by Student_id")
psycopg2.errors.UndefinedColumn: column "student_id" does not exist
LINE 1: select Student_id, sum(month_fees) as sum_month_fees from sh...
               ^
HINT:  Perhaps you meant to reference the column "shikshalaya_computer_app_computer_student_monthly_fees.Student_id".

INFO  2022-08-03 19:51:42,640 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 19:52:30,435 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 19:53:19,532 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 469, in VIEW_COMPUTER_STUDENT
    data_result_mf = mf.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
INFO  2022-08-03 19:55:34,456 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
WARNING  2022-08-03 19:55:45,798 Forbidden (CSRF token from POST incorrect.): /doLogin/
ERROR  2022-08-03 19:56:03,715 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 469, in VIEW_COMPUTER_STUDENT
    data_result_mf = mf.fetchmany()
AttributeError: 'NoneType' object has no attribute 'fetchmany'
INFO  2022-08-03 19:57:54,340 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 19:58:08,087 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 474, in VIEW_COMPUTER_STUDENT
    data_result_cf = cf.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
INFO  2022-08-03 19:58:27,036 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:27:19,257 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:36:11,750 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:36:14,408 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-03 20:40:09,522 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-03 20:49:46,162 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-03 20:50:14,693 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-03 20:52:14,666 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:53:06,478 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:53:18,490 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:54:32,060 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 20:55:34,642 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:00:14,658 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:01:10,792 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:01:32,886 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:02:21,948 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:09:29,975 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:09:49,306 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:10:13,913 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:11:36,561 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:13:20,827 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:17:45,052 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:19:36,779 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:20:21,955 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:20:41,569 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:23:08,065 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:23:18,866 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-03 21:23:42,344 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 21:24:09,131 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-03 21:24:51,144 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
INFO  2022-08-03 21:26:12,694 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-03 21:26:16,108 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-03 21:33:25,902 Internal Server Error: /doLogin/
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "shikshalaya_computer_app_customuser" does not exist
LINE 1: ...alaya_computer_app_customuser"."profile_pic" FROM "shikshala...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\views.py", line 23, in doLogin
    user = EmailBackEnd.authenticate(request,username = request.POST.get('email'),password = request.POST.get('password'))
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\EmailBackEnd.py", line 9, in authenticate
    user = UserModel.objects.get(email=username)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 492, in get
    num = len(clone)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 302, in __len__
    self._fetch_all()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "shikshalaya_computer_app_customuser" does not exist
LINE 1: ...alaya_computer_app_customuser"."profile_pic" FROM "shikshala...
                                                             ^

ERROR  2022-08-03 21:40:40,103 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

INFO  2022-08-04 12:58:30,483 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 12:59:14,605 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 13:00:14,636 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

WARNING  2022-08-04 13:00:14,942 Not Found: /favicon.ico
ERROR  2022-08-04 13:01:57,961 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

ERROR  2022-08-04 13:02:28,333 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

INFO  2022-08-04 13:03:15,744 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 13:03:55,231 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

INFO  2022-08-04 13:05:26,539 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
INFO  2022-08-04 13:06:05,346 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
ERROR  2022-08-04 13:07:25,512 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

ERROR  2022-08-04 13:08:22,804 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

ERROR  2022-08-04 13:12:57,272 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "father_mobile" of relation "shikshalaya_computer_app_computer_student" violates not-null constraint
DETAIL:  Failing row contains (2, Male, 2022-08-19, , 1, 11111, , , null, , , null, , , 2022-08-07, 2022-08-07, 700, 1700, August, 2022-08-04 07:42:56.328048+00, 2022-08-04 07:42:56.328048+00, 10, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "father_mobile" of relation "shikshalaya_computer_app_computer_student" violates not-null constraint
DETAIL:  Failing row contains (2, Male, 2022-08-19, , 1, 11111, , , null, , , null, , , 2022-08-07, 2022-08-07, 700, 1700, August, 2022-08-04 07:42:56.328048+00, 2022-08-04 07:42:56.328048+00, 10, 1).

INFO  2022-08-04 13:14:42,179 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
INFO  2022-08-04 13:15:25,487 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
ERROR  2022-08-04 13:17:10,573 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

INFO  2022-08-04 13:20:21,805 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
ERROR  2022-08-04 13:22:37,857 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: value "7838540909" is out of range for type integer
LINE 1: ...pdated_at") VALUES (13, 'Male', '2022-08-19', '', '783854090...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value "7838540909" is out of range for type integer
LINE 1: ...pdated_at") VALUES (13, 'Male', '2022-08-19', '', '783854090...
                                                             ^

ERROR  2022-08-04 13:25:34,648 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: value "9899011752" is out of range for type integer
LINE 1: ...pdated_at") VALUES (14, 'Male', '2022-08-28', '', '989901175...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value "9899011752" is out of range for type integer
LINE 1: ...pdated_at") VALUES (14, 'Male', '2022-08-28', '', '989901175...
                                                             ^

ERROR  2022-08-04 13:27:31,202 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: value "+919899011752" is out of range for type integer
LINE 1: ...pdated_at") VALUES (15, 'Male', '2022-08-26', '', '+91989901...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value "+919899011752" is out of range for type integer
LINE 1: ...pdated_at") VALUES (15, 'Male', '2022-08-26', '', '+91989901...
                                                             ^

ERROR  2022-08-04 13:29:06,343 Internal Server Error: /Hod/Computer/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: value "9899011752" is out of range for type integer
LINE 1: ...ated_at") VALUES (16, 'Female', '2022-08-25', '', '989901175...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 449, in ADD_COMPUTER_STUDENT
    student.save()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value "9899011752" is out of range for type integer
LINE 1: ...ated_at") VALUES (16, 'Female', '2022-08-25', '', '989901175...
                                                             ^

INFO  2022-08-04 13:31:36,597 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 13:32:46,443 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
WARNING  2022-08-04 14:27:51,845 Not Found: /Hod/Course/add-student.html
ERROR  2022-08-04 14:29:44,273 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 484, in rem
    rem_fee.append((int(cf1[0]), cf1[1] - mf1[1]))
TypeError: unsupported operand type(s) for -: 'str' and 'int'
ERROR  2022-08-04 14:29:55,386 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 484, in rem
    rem_fee.append((int(cf1[0]), cf1[1] - mf1[1]))
TypeError: unsupported operand type(s) for -: 'str' and 'int'
ERROR  2022-08-04 15:10:02,294 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 484, in rem
    rem_fee.append((int(cf1[0]), cf1[1] - mf1[1]))
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:11:06,752 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:11:10,575 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 484, in rem
    rem_fee.append((cf1[0], cf1[1] - mf1[1]))
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:11:30,397 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:11:33,405 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 484, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:12:12,792 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:12:16,873 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 488, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 485, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:12:52,788 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:12:55,156 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 488, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 485, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:13:49,487 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:14:15,839 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:14:18,561 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 488, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 485, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:14:48,715 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:14:50,917 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 488, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 485, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:15:21,607 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:15:29,481 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:16:00,383 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:16:48,870 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:17:19,596 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:17:40,072 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:17:42,533 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 490, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:17:59,465 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:18:12,598 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 15:47:34,177 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 490, in VIEW_COMPUTER_STUDENT
    rem_fee = rem(data_result_cf, data_result_mf)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 487, in rem
    rem_fee.append([cf1[0], cf1[1] - mf1[1]])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
INFO  2022-08-04 15:48:20,475 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:50:22,195 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
INFO  2022-08-04 15:52:21,537 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
INFO  2022-08-04 15:54:02,411 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 15:54:11,456 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 16:00:51,098 Internal Server Error: /Hod/Student/Add
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 50, in ADD_STUDENT
    print(profile_pic,first_name,last_name,email,username,password,gender,date_of_birth,Class,joining_date,mobile_number,admission_number,father_name,father_occupation,father_mobile_number,mother_name,mother_mobile_number,mother_occupation,present_address,permenent_address,course_id,course,session_start,session_end,course_fees)
NameError: name 'father_name' is not defined
INFO  2022-08-04 16:01:44,426 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 16:04:16,828 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-04 16:04:20,325 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
INFO  2022-08-04 16:11:39,198 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 16:11:51,395 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 16:12:03,561 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 16:12:19,813 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 16:14:23,538 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 16:23:43,091 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-04 16:25:09,511 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-04 16:26:41,002 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-04 16:27:23,344 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-04 16:41:05,778 Internal Server Error: /Hod/Computer/Student/Fees_Month
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 663, in FEES_RECEIPT_COMPUTER_STUDENT_MONTH
    return render(request, 'Hod/student_fees_month_check.html', context)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\template\base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' == r.Student_id' from 'i.id == r.Student_id'
INFO  2022-08-04 16:59:00,913 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\shikshalaya_computer_app\models.py changed, reloading.
INFO  2022-08-04 17:05:11,733 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 17:05:21,831 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 17:05:30,835 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 17:05:45,064 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-04 17:13:59,054 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-04 17:16:08,769 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 462, in VIEW_COMPUTER_STUDENT
    conn = psycopg2.connect(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "ec2-54-152-28-9.compute-1.amazonaws.com" (54.152.28.9), port 5432 failed: FATAL:  password authentication failed for user "calqkupkwsvngs"
connection to server at "ec2-54-152-28-9.compute-1.amazonaws.com" (54.152.28.9), port 5432 failed: FATAL:  no pg_hba.conf entry for host "106.202.113.78", user "calqkupkwsvngs", database "d3bmfac0uaodn6", no encryption

INFO  2022-08-04 17:17:10,233 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-04 17:20:30,750 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-05 11:51:59,047 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
ERROR  2022-08-05 11:53:08,335 Internal Server Error: /Hod/Computer/Student/View
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py", line 462, in VIEW_COMPUTER_STUDENT
    conn = psycopg2.connect(
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "ec2-54-152-28-9.compute-1.amazonaws.com" (54.152.28.9), port 5432 failed: FATAL:  password authentication failed for user "jcnsowkypgbkok"
connection to server at "ec2-54-152-28-9.compute-1.amazonaws.com" (54.152.28.9), port 5432 failed: FATAL:  no pg_hba.conf entry for host "106.202.70.177", user "jcnsowkypgbkok", database "dembhfve0a83tr", no encryption

WARNING  2022-08-05 11:53:08,557 Not Found: /favicon.ico
INFO  2022-08-05 11:56:08,669 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-05 11:57:19,544 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-05 11:57:33,736 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
INFO  2022-08-05 11:57:41,667 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
ERROR  2022-08-05 12:03:17,024 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
ERROR  2022-08-05 12:03:20,462 Internal Server Error: /Hod/Computer/Sallary
Traceback (most recent call last):
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view student_management_system.Hod_views.COMPUTER_SALLARY didn't return an HttpResponse object. It returned None instead.
INFO  2022-08-05 12:47:25,705 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-05 12:47:42,967 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-05 12:49:11,663 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\settings.py changed, reloading.
INFO  2022-08-05 13:17:09,854 E:\OneDrive - student.amity.edu\office\python & R\Shikshalaya\shikshalaya_web\student_management_system\student_management_system\Hod_views.py changed, reloading.
